### ISSUE TITLE
Video is not available in your country - Lecture 4: Seam carving live coding session

### ISSUE THREAD

**Issue by JohannesNE** [mitmath/18S191#28]
When I try to watch Lecture 4 from Denmark.
YouTube just gives the message: "This video is not available in your country"

**Comment by leios** [comment]
I checked video availability, and it said we are distributing everywhere, so Denmark might be blocking it for some reason? The only thing I could think of was that this could be because we had music playing for the first 5 minutes. The music is under a CC-BY license and I use it all the time in my videos without any issues, so I doubt that's the case, but I removed the first 5 minutes just in case.

Would you be able to check back tomorrow morning your time?

**Comment by JohannesNE** [comment]
Thanks. 

There is an ongoing struggle between YT and the danish musicians organization (KODA), resulting in the removal danish music from YT, but reportedly also a lot of collateral damage (https://support.google.com/youtube/thread/62491239?hl=en)

I'll check tomorrow.

**Comment by leios** [comment]
Yeah, I found that thread as well! There was no discussion in the 5 minutes I cut out. It actually makes the video way better this way.

Please let us know if it's still unavailable and I can keep digging!

**Comment by JohannesNE** [comment]
I can access it now. Thanks a lot for the fast effort.

**Comment by leios** [comment]
Ok, that's really interesting. I don't know why that music sets off any alarms. Out of curiosity, are you able to watch any videos from my channel (https://www.youtube.com/user/leiosos)?

It uses the same background music (which is Creative Commons and I also paid licensing for to be safe).

**Comment by JohannesNE** [comment]
I looked through a couple of them yesterday without any problem (good work btw :+1: ). Just tried sampling ~10 of them now. All run fine.
