### ISSUE TITLE
seam_carving.jl

### ISSUE THREAD

**Issue by 1rdsk1** [mitmath/18S191#57]
Hi, I am running Pluto in chrome on windows 10 and get following error on the third code block.  Is it possible to run the code on windows?  curl.exe is installed.
failed process: Process(`'C:\WINDOWS\System32\curl.exe' -s -S -g -L -f -o 'C:\Users\ruper\AppData\Local\Temp\jl_2fRSvgqCWA' https://cdn.shortpixel.ai/spai/w_1086+q_lossy+ret_img+to_webp/https://wisetoast.com/wp-content/uploads/2015/10/The-Persistence-of-Memory-salvador-deli-painting.jpg`, ProcessExited(35)) [35]

pipeline_error@process.jl:525[inlined]
download_curl(::String, ::String, ::String)@download.jl:44
download@download.jl:62[inlined]
download(::String)@download.jl:89
top-level scope@Local: 17[inlined]

**Comment by BrandonConder** [comment]
It looks like there's [an upstream issue](https://github.com/JuliaLang/julia/issues/35660) with download.jl in Julia Base.

download.jl calls curl with single-quotes (') and Windows cmd.exe requires double-quotation marks (").
It looks like in the command line it works if you replace single quotes with double-quotes.

I'm not fully set up to do testing on Windows so I'm not sure exactly what will work.

Could you try editing the bad cell to use `download_powershell` instead of `download`?

**Comment by fonsp** [comment]
It sounds like this was a university/government firewall, or just a "flaky connection" or "internet weather". 

We tried looking for a more stable website to use, like wikimedia: https://en.wikipedia.org/wiki/File:The_Persistence_of_Memory.jpg
but there are only low-resolution versions available, because the work is not yet in the public domain (1931).

The link we used is high-resolution, because it is actually not the work by Salvador Dali, it is a replica! (Posted online by the author)

I have updated the notebook to not use a redirect anymore, which might help, but there's nothing more we can do.
